### ISSUE TITLE
Unable to run the sample app within the repo

### ISSUE THREAD

**Issue by hmaster0** [juananime/react-native-audiowaveform#25]
I cloned the repo and moved into the `Example` directory, installed all dependencies via yarn, started packager using `react-native start` and then built the app using `react-native run-android`.
The app built successfully but as soon as the app starts on the device it throws this exception :-
![waveform_sample_exception_2](https://user-images.githubusercontent.com/10733612/29676868-ed87656a-8916-11e7-9131-da1e6fe95f46.png)
I then tried to fix this by navigating to react-native-audiowaveform directory inside the node_modules directory and define a propType for `componentID` like this :-
```
const WaveForm = React.createClass({
    propTypes: {
        ...View.propTypes,
        componentID:React.PropTypes.string,
        autoPlay:React.PropTypes.bool,
        waveFormStyle:PropTypes.shape({
            leftWaveColor: React.PropTypes.string,
            rightWaveColor: React.PropTypes.string
        }),
```
When I rebuilt the app, the exception changed to :-
![waveform_sample_exception_1](https://user-images.githubusercontent.com/10733612/29677156-e0806b36-8917-11e7-96bf-f051d5984084.png)
Please advise about how to get this sample application up and running and what's wrong that's causing these issues. Thank you.

**Comment by hmaster0** [comment]
Hey @juananime, any updates on this yet? I need this plugin to work with RN 0.48, can you help me out here?

**Comment by jagdishadusumalli** [comment]
+1

**Comment by prakashsejwani** [comment]
+1

**Comment by themakerman** [comment]
+1. Forget the example app. The library has compilation errors.

**Comment by juananime** [comment]
I’m checking this issue today. I’ll keep you posted. Cheers

**Comment by hmaster0** [comment]
@juananime Hope that you make it work with RN 0.48

**Comment by juananime** [comment]
Hello, I took a look to that issue, I made it work in my android device. Its updated at the NPM repo and at GitHub as well.
I found a missing method in the WaveformView.WaveformListener interface.
Please let me know how its working for you.
Cheers!

**Comment by themakerman** [comment]
@juananime ok thanks. gonna try tonight. Will update you.

**Comment by themakerman** [comment]
@juananime Ok compiling on android now. I am seeing an error of waveFormStyle.rightWaveColor now. The props which are documented (wavecolor and scrubcolor) are not working as well. When i change the values they are not being reflected.

This is my code now. If i am eliminating rightWaveColor prop which is nowhere specified in the documentation as mandatory i am not able to see the waveform.

```
<WaveForm
         autoPlay
         source={require('./wildbot.mp3')}
         waveFormStyle={{ rightWaveColor: 'red', waveColor: 'red', scrubColor: 'red' }}
         style={{ width: 500, height: 50 }}
        />
```
